# ruff: noqa: E501
"""Область обхода (ADR-020, docs/product-hunter-blueprint.md): каждая категория карты Avito ровно в одной области.

Ключ — путь (и запрос) категории без домена: стабилен между установками, в отличие от id в БД.
CORE — ежедневно; WATCH и QUERY — раз в 2 дня, 1 страница; EXPLORE — ротация раз в ~10 дней;
OFF — 0 запросов (пересмотр вручную); HARD_EXCLUDE — никогда (регулирование / несовместимо с моделью).
Сгенерировано из карты 2026-10-04 и согласованного списка; правится руками.
"""

SCOPES = ("CORE", "WATCH", "QUERY", "EXPLORE", "OFF", "HARD_EXCLUDE")
ACTIVE = ("CORE", "WATCH", "QUERY", "EXPLORE")  # обходятся (с разной частотой)

# key: (scope, name, flags, duplicate_of)
SCOPE: dict[str, tuple[str, str, str, str | None]] = {
    "/rossiya/velosipedy/zapchasti_i_aksessuary-ASgBAgICAUS4AqQK": (
        "CORE",
        "Аксессуары и запчасти для велосипедов",
        "",
        None,
    ),
    "/rossiya/zapchasti_i_aksessuary/audio-_i_videotehnika-ASgBAgICAUQKKA": (
        "CORE",
        "Аудио- и видеотехника для авто",
        "",
        None,
    ),
    "/rossiya/velosipedy/gornye-ASgBAgICAUS4AqgK": ("CORE", "Горные велосипеды", "", None),
    "/rossiya/zapchasti_i_aksessuary/zashita_i_dekor-ASgBAgICAkQKnk2qlRPM5I0D": (
        "CORE",
        "Защита и декор для автомобиля",
        "",
        None,
    ),
    "/rossiya/igry_pristavki_i_programmy/igrovye_pristavki-ASgBAgICAUSSAsoJ": (
        "CORE",
        "Игровые приставки и аксессуары",
        "",
        None,
    ),
    "/rossiya/noutbuki/asus-ASgBAgICAUSo5A222WY": ("CORE", "Ноутбуки ASUS", "", None),
    "/rossiya/noutbuki/honor-ASgBAgICAUSo5A2S2mY": ("CORE", "Ноутбуки HONOR", "", None),
    "/rossiya/noutbuki/huawei-ASgBAgICAUSo5A2C2mY": ("CORE", "Ноутбуки HUAWEI", "", None),
    "/rossiya/noutbuki/lenovo-ASgBAgICAUSo5A3m2WY": ("CORE", "Ноутбуки Lenovo", "", None),
    "/rossiya/noutbuki/msi-ASgBAgICAUSo5A202WY": ("CORE", "Ноутбуки MSI", "", None),
    "/rossiya/noutbuki/thunderobot-ASgBAgICAUSo5A2a4q0Q": ("CORE", "Ноутбуки Thunderobot", "", None),
    "/rossiya/noutbuki/xiaomi-ASgBAgICAUSo5A2A2mY": ("CORE", "Ноутбуки Xiaomi", "", None),
    "/rossiya/audio_i_video/plenocnye_kamery-ASgBAgICAkSIAroJ0sYXtrKaAw": ("CORE", "Плёночные камеры", "", None),
    "/rossiya/fototehnika/zerkalnye_fotoapparaty-ASgBAgICAUS~A7AX": (
        "CORE",
        "Продажа зеркальных фотоаппаратов",
        "",
        None,
    ),
    "/rossiya/fototehnika/kompaktnye_fotoapparaty-ASgBAgICAUS~A7IX": (
        "CORE",
        "Продажа компактных фотоаппаратов",
        "",
        None,
    ),
    "/rossiya/tovary_dlya_kompyutera/komplektuyuschie-ASgBAgICAUTGB~pm": (
        "CORE",
        "Продажа компьютерных комплектующих",
        "",
        None,
    ),
    "/rossiya/fototehnika/obektivy-ASgBAgICAUS~A6YX": ("CORE", "Продажа объективов для фотоаппаратов", "", None),
    "/rossiya/fototehnika/plenochnye_fotoapparaty-ASgBAgICAUS~A6gX": (
        "CORE",
        "Продажа плёночных фотоаппаратов",
        "",
        None,
    ),
    "/rossiya/tovary_dlya_kompyutera/dzhoystiki_i_ruli-ASgBAgICAUTGB7ZO": (
        "CORE",
        "Рули и джойстики для компьютеров и приставок",
        "",
        None,
    ),
    "/rossiya/muzykalnye_instrumenty/dlya_studii_i_kontsertov-ASgBAgICAUTEAsgK": (
        "CORE",
        "Студийное и концертное оборудование",
        "",
        None,
    ),
    "/rossiya/audio_i_video/cifrovye_kamery-ASgBAgICAkSIAroJ0sYXsrKaAw": ("CORE", "Цифровые камеры", "", None),
    "/rossiya/zapchasti_i_aksessuary/shiny_diski_i_kolesa-ASgBAgICAUQKJg": (
        "CORE",
        "Шины, диски и колёса",
        "LOGISTICS_CHECK",
        None,
    ),
    "/rossiya/velosipedy/shosseinye-ASgBAgICAUS4Aq4K": ("CORE", "Шоссейные велосипеды", "", None),
    "/rossiya/audio_i_video/eksn_kamery-ASgBAgICAkSIAroJ0sYXtLKaAw": ("CORE", "Экшн-камеры", "", None),
    "/rossiya/velosipedy/elektrovelosipedy-ASgBAgICAUS4Ap72lwM": ("CORE", "Электровелосипеды", "LOGISTICS_CHECK", None),
    "/rossiya/tovary_dlya_detey_i_igrushki/detskie_kolyaski-ASgBAgICAUT~AZgJ": (
        "WATCH",
        "Детские коляски",
        "LOGISTICS_CHECK",
        None,
    ),
    "/rossiya/muzykalnye_instrumenty/klavishnye_i_sintezatory-ASgBAgICAUTEAswK": (
        "WATCH",
        "Клавишные инструменты и синтезаторы",
        "",
        None,
    ),
    "/rossiya/kollektsionirovanie/igry-ASgBAgICAUQcjAE": ("WATCH", "Коллекционные игрушки и игры", "", None),
    "/rossiya/kollektsionirovanie/modeli_figurki_kukly-ASgBAgICAUQcmAE": (
        "WATCH",
        "Модели, фигурки, куклы",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/obuv_muzhskaya-ASgBAgICAUTeArqp1gI": ("WATCH", "Мужская обувь", "", None),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL": ("WATCH", "Мужская одежда", "", None),
    "/rossiya/audio_i_video/naushniki-ASgBAgICAUSIAtRO": ("WATCH", "Наушники и гарнитуры", "FAKE_RISK", None),
    "/rossiya/fototehnika/binokli_i_teleskopy-ASgBAgICAUS~A6IX": (
        "WATCH",
        "Продажа биноклей, телескопов, подзорных труб",
        "REGULATORY_CHECK",
        None,
    ),
    "/rossiya/planshety_i_elektronnye_knigi/planshety-ASgBAgICAUSYAoZO": ("WATCH", "Продажа планшетов", "", None),
    "/rossiya/telefony/ratsiya-ASgBAgICAUSwwQ2K_Dc": ("WATCH", "Рации", "", None),
    "/rossiya/sport_i_otdyh/samokaty_i_giroskutery-ASgBAgICAUTKAvS5lwM": (
        "WATCH",
        "Самокаты и гироскутеры",
        "LOGISTICS_CHECK",
        None,
    ),
    "/rossiya/telefony/smart_chasy_i_fitnes_braslety-ASgBAgICAUSwwQ3IxpsD": (
        "WATCH",
        "Смарт-часы и фитнес-браслеты",
        "",
        None,
    ),
    "/rossiya/telefony/mobile-ASgBAgICAUSwwQ2I_Dc": ("WATCH", "Смартфоны и мобильные телефоны", "", None),
    "/rossiya/telefony/iphone-ASgBAgICAUSeAt4J": ("WATCH", "Смартфоны и мобильные телефоны Apple", "FAKE_RISK", None),
    "/rossiya/ohota_i_rybalka/ohota-ASgBAgICAUSY5hTkiZAD": ("WATCH", "Снаряжение для охоты", "REGULATORY_CHECK", None),
    "/rossiya/odezhda_obuv_aksessuary/sumki_ryukzaki_i_chemodany-ASgBAgICAUTeArip1gI": (
        "WATCH",
        "Сумки, рюкзаки и чемоданы",
        "",
        None,
    ),
    "/rossiya/audio_i_video/usiliteli_i_resivery-ASgBAgICAUSIArYJ": ("WATCH", "Усилители и ресиверы", "", None),
    "/rossiya/chasy_i_ukrasheniya/chasy-ASgBAgICAUTQAYYG": ("WATCH", "Часы", "FAKE_RISK", None),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=acne+studios": (
        "QUERY",
        "Acne Studios — муж.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=arcteryx": (
        "QUERY",
        "Arcteryx — муж.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=balenciaga": (
        "QUERY",
        "Balenciaga — муж.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=cp+company": (
        "QUERY",
        "CP Company — муж.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=chrome+hearts": (
        "QUERY",
        "Chrome Hearts — муж.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=fear+of+god+essentials": (
        "QUERY",
        "Fear of God Essentials — муж.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=gucci": (
        "QUERY",
        "Gucci — муж.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=louis+vuitton": (
        "QUERY",
        "Louis Vuitton — муж.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=maison+margiela": (
        "QUERY",
        "Maison Margiela — муж.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=miu+miu": (
        "QUERY",
        "Miu Miu — жен.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=moncler": (
        "QUERY",
        "Moncler — муж.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=prada": (
        "QUERY",
        "Prada — муж.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=represent": (
        "QUERY",
        "Represent — муж.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=rick+owens": (
        "QUERY",
        "Rick Owens — жен.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=rick+owens": (
        "QUERY",
        "Rick Owens — муж.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=stone+island": (
        "QUERY",
        "Stone Island — муж.",
        "FAKE_RISK",
        None,
    ),
    "/rossiya/velosipedy/bmx-ASgBAgICAUS4AqYK": ("EXPLORE", "BMX велосипеды", "", None),
    "/rossiya/odezhda_obuv_aksessuary/kupit-aksessuary-ASgBAgICAUTeAtoL": (
        "EXPLORE",
        "Аксессуары для женщин и мужчин",
        "",
        None,
    ),
    "/rossiya/zapchasti_i_aksessuary/dlya_kolyos-ASgBAgICAkQKnk2qlRPQ5I0D": (
        "EXPLORE",
        "Аксессуары для колес для автомобиля",
        "",
        None,
    ),
    "/rossiya/muzykalnye_instrumenty/aksessuary-ASgBAgICAUTEAtAK": (
        "EXPLORE",
        "Аксессуары для музыкальных инструментов",
        "",
        None,
    ),
    "/rossiya/zapchasti_i_aksessuary/dlya_salona-ASgBAgICAkQKnk2qlRPK5I0D": (
        "EXPLORE",
        "Аксессуары для салона автомобиля",
        "",
        None,
    ),
    "/rossiya/audio_i_video/akustika_kolonki_sabvufery-ASgBAgICAUSIAsxO": (
        "EXPLORE",
        "Акустика, колонки и сабвуферы",
        "",
        None,
    ),
    "/rossiya/zapchasti_i_aksessuary/bagazhniki_i_farkopy-ASgBAgICAUQKyE0": (
        "EXPLORE",
        "Багажники и фаркопы",
        "",
        None,
    ),
    "/rossiya/bytovaya_tehnika/drugoe-ASgBAgICAURgvgs": ("EXPLORE", "Бытовая техника", "", None),
    "/rossiya/bytovaya_tehnika/dlya_doma-ASgBAgICAURgpE8": ("EXPLORE", "Бытовая техника для дома", "", None),
    "/rossiya/audio_i_video/videokamery-ASgBAgICAUSIAroJ": ("EXPLORE", "Видеокамеры", "", None),
    "/rossiya/muzykalnye_instrumenty/gitary_i_strunnye-ASgBAgICAUTEAsYK": (
        "EXPLORE",
        "Гитары, струнные инструменты",
        "",
        None,
    ),
    "/rossiya/velosipedy/gorodskie-ASgBAgICAUS4AuLTkAM": ("EXPLORE", "Городские велосипеды", "", None),
    "/rossiya/tovary_dlya_detey_i_igrushki/avtomobilnye_kresla-ASgBAgICAUT~AZIJ": (
        "EXPLORE",
        "Детские автокресла",
        "REGULATORY_CHECK",
        None,
    ),
    "/rossiya/muzykalnye_instrumenty/duhovye-ASgBAgICAUTEAsoK": ("EXPLORE", "Духовые инструменты", "", None),
    "/rossiya/odezhda_obuv_aksessuary/obuv_zhenskaya-ASgBAgICAUTeAryp1gI": ("EXPLORE", "Женская обувь", "", None),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL": ("EXPLORE", "Женская одежда", "", None),
    "/rossiya/tovary_dlya_kompyutera/klaviatury_i_myshi-ASgBAgICAUTGB7xO": ("EXPLORE", "Клавиатуры и мыши", "", None),
    "/rossiya/bytovaya_tehnika/klimaticheskoe_oborudovanie-ASgBAgICAURguE8": (
        "EXPLORE",
        "Климатическое оборудование",
        "",
        None,
    ),
    "/rossiya/mebel_i_interer/kompyuternye_stoly_i_kresla-ASgBAgICAURa0E8": (
        "EXPLORE",
        "Компьютерные столы и кресла",
        "",
        None,
    ),
    "/rossiya/bytovaya_tehnika/dlya_kuhni-ASgBAgICAURglk8": ("EXPLORE", "Кухонная техника", "", None),
    "/rossiya/audio_i_video/mikrofony-radiosistemy-i-aksessuary-ASgBAgICAUSIAtBO": (
        "EXPLORE",
        "Микрофоны, радиосистемы и аксессуары",
        "",
        None,
    ),
    "/rossiya/tovary_dlya_kompyutera/monitory_i_zapshasty-ASgBAgICAUTGB4Bo": (
        "EXPLORE",
        "Мониторы и запчасти",
        "",
        None,
    ),
    "/rossiya/nastolnye_kompyutery/monobloki-ASgBAgICAUS02xKOqY0D": ("EXPLORE", "Моноблоки", "", None),
    "/rossiya/nastolnye_kompyutery/novyy-ASgBAgICAUTuvA2C0jQ": ("EXPLORE", "Новый компьютер", "", None),
    "/rossiya/ohota_i_rybalka/nozhi_multituly_topory-ASgBAgICAUSY5hTiiZAD": (
        "EXPLORE",
        "Ножи, мультитулы, топоры для охоты и рыбалки",
        "REGULATORY_CHECK",
        None,
    ),
    "/rossiya/noutbuki/acer-ASgBAgICAUSo5A3C2WY": ("EXPLORE", "Ноутбуки Acer", "", None),
    "/rossiya/noutbuki/alienware-ASgBAgICAUSo5A2Q2mY": ("EXPLORE", "Ноутбуки Alienware", "", None),
    "/rossiya/noutbuki/apple-ASgBAgICAUSo5A302WY": ("EXPLORE", "Ноутбуки Apple", "", None),
    "/rossiya/noutbuki/bliss-ASgBAgICAUSo5A2G2mY": ("EXPLORE", "Ноутбуки Bliss", "", None),
    "/rossiya/noutbuki/dell-ASgBAgICAUSo5A3U2WY": ("EXPLORE", "Ноутбуки DELL", "", None),
    "/rossiya/noutbuki/evga-ASgBAgICAUSo5A2m2mY": ("EXPLORE", "Ноутбуки EVGA", "", None),
    "/rossiya/noutbuki/hp-ASgBAgICAUSo5A3A2WY": ("EXPLORE", "Ноутбуки HP", "", None),
    "/rossiya/noutbuki/samsung-ASgBAgICAUSo5A3G2WY": ("EXPLORE", "Ноутбуки Samsung", "", None),
    "/rossiya/noutbuki/vitumi-ASgBAgICAUSo5A3OnoUV": ("EXPLORE", "Ноутбуки Vitumi", "", None),
    "/rossiya/zapchasti_i_aksessuary/otopitelnoe_oborudovanie-ASgBAgICAkQKnk2qlRPS5I0D": (
        "EXPLORE",
        "Отопительное оборудование для автомобиля",
        "",
        None,
    ),
    "/rossiya/krasota_i_zdorove/pribory_i_aksessuary-ASgBAgICAUSEAqAJ": (
        "EXPLORE",
        "Приборы и аксессуары для красоты и здоровья",
        "",
        None,
    ),
    "/rossiya/fototehnika/oborudovanie_i_aksessuary-ASgBAgICAUS~A64X": (
        "EXPLORE",
        "Продажа аксессуаров для фототехники",
        "",
        None,
    ),
    "/rossiya/zapchasti_i_aksessuary/zapchasti-ASgBAgICAUQKJA": (
        "EXPLORE",
        "Продажа запчастей во всех регионах",
        "",
        None,
    ),
    "/rossiya/tovary_dlya_kompyutera/setevoe_oborudovanie-ASgBAgICAUTGB75O": (
        "EXPLORE",
        "Продажа сетевого оборудования",
        "",
        None,
    ),
    "/rossiya/zapchasti_i_aksessuary/protivougonnye_ustroystva-ASgBAgICAUQKoE0": (
        "EXPLORE",
        "Противоугонные устройства для автомобиля",
        "",
        None,
    ),
    "/rossiya/sport_i_otdyh/roliki_i_skeytbording-ASgBAgICAUTKAopP": (
        "EXPLORE",
        "Ролики, скейтборды, защита",
        "",
        None,
    ),
    "/rossiya/nastolnye_kompyutery/sistemnye_bloki-ASgBAgICAUS02xKMqY0D": ("EXPLORE", "Системные блоки", "", None),
    "/rossiya/muzykalnye_instrumenty/skripki_i_smychkovye-ASgBAgICAUTEAvRO": (
        "EXPLORE",
        "Скрипки, смычковые инструменты",
        "",
        None,
    ),
    "/rossiya/sport_i_otdyh/strelkovyi_sport-ASgBAgICAUTKAohP": (
        "EXPLORE",
        "Снаряжение для стрелкового спорта",
        "REGULATORY_CHECK",
        None,
    ),
    "/rossiya/sport_i_otdyh/turizm_i_otdyh_na_prirode-ASgBAgICAUTKAt4K": (
        "EXPLORE",
        "Снаряжение для туризма и отдыха на природе",
        "",
        None,
    ),
    "/rossiya/sport_i_otdyh/fitnes_i_trenazhery-ASgBAgICAUTKAuAK": (
        "EXPLORE",
        "Спортивные тренажеры, товары для фитнеса",
        "",
        None,
    ),
    "/rossiya/remont_i_stroitelstvo/instrumenty-ASgBAgICAURYoks": ("EXPLORE", "Строительные инструменты", "", None),
    "/rossiya/audio_i_video/televizory_i_proektory-ASgBAgICAUSIArgJ": ("EXPLORE", "Телевизоры и проекторы", "", None),
    "/rossiya/sport_i_otdyh/dayving_i_vodnyy_sport-ASgBAgICAUTKAtgK": (
        "EXPLORE",
        "Товары для водного спорта",
        "",
        None,
    ),
    "/rossiya/sport_i_otdyh/zimniy_sport-ASgBAgICAUTKAtoK": ("EXPLORE", "Товары для зимнего спорта", "", None),
    "/rossiya/bytovaya_tehnika/dlya_individualnogo_uhoda-ASgBAgICAURgrk8": (
        "EXPLORE",
        "Товары для индивидуального ухода",
        "",
        None,
    ),
    "/rossiya/muzykalnye_instrumenty/udarnye-ASgBAgICAUTEAs4K": ("EXPLORE", "Ударные", "", None),
    "/rossiya/zapchasti_i_aksessuary/ekipirovka-ASgBAgICAUQKoGQ": (
        "EXPLORE",
        "Экипировка для авто- и мотоспорта",
        "",
        None,
    ),
    "/rossiya/zapchasti_i_aksessuary/dlya_moto__i_vodnogo_transporta-ASgBAgICAkQKnk2qlRPW5I0D": (
        "EXPLORE",
        "мото/водный транспорт: запчасти",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=acne+studios": (
        "OFF",
        "Acne Studios — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=arcteryx": (
        "OFF",
        "Arcteryx — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=balenciaga": (
        "OFF",
        "Balenciaga — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=bottega+veneta": (
        "OFF",
        "Bottega Veneta — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=bottega+veneta": (
        "OFF",
        "Bottega Veneta — муж.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=brunello+cucinelli": (
        "OFF",
        "Brunello Cucinelli — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=brunello+cucinelli": (
        "OFF",
        "Brunello Cucinelli — муж.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=burberry": (
        "OFF",
        "Burberry — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=burberry": (
        "OFF",
        "Burberry — муж.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=cp+company": (
        "OFF",
        "CP Company — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=celine": ("OFF", "Celine — жен.", "", None),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=celine": ("OFF", "Celine — муж.", "", None),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=chrome+hearts": (
        "OFF",
        "Chrome Hearts — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=dior": ("OFF", "Dior — жен.", "", None),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=dior": ("OFF", "Dior — муж.", "", None),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=fear+of+god+essentials": (
        "OFF",
        "Fear of God Essentials — жен.",
        "",
        None,
    ),
    "/rossiya/zapchasti_i_aksessuary/gps-navigatory-ASgBAgICAUQKKg": ("OFF", "GPS-навигаторы для автомобиля", "", None),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=gucci": ("OFF", "Gucci — жен.", "", None),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=loro+piana": (
        "OFF",
        "Loro Piana — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=loro+piana": (
        "OFF",
        "Loro Piana — муж.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=louis+vuitton": (
        "OFF",
        "Louis Vuitton — жен.",
        "",
        None,
    ),
    "/rossiya/audio_i_video/mp3-pleery-ASgBAgICAUSIArIJ": ("OFF", "MP3-плееры", "", None),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=maison+margiela": (
        "OFF",
        "Maison Margiela — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=max+mara": (
        "OFF",
        "Max Mara — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=max+mara": (
        "OFF",
        "Max Mara — муж.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=miu+miu": (
        "OFF",
        "Miu Miu — муж.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=moncler": (
        "OFF",
        "Moncler — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=prada": ("OFF", "Prada — жен.", "", None),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=represent": (
        "OFF",
        "Represent — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=saint+laurent": (
        "OFF",
        "Saint Laurent — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=saint+laurent": (
        "OFF",
        "Saint Laurent — муж.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=stone+island": (
        "OFF",
        "Stone Island — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/zhenskaya_odezhda-ASgBAgICAUTeAtYL?q=vetements": (
        "OFF",
        "Vetements — жен.",
        "",
        None,
    ),
    "/rossiya/odezhda_obuv_aksessuary/muzhskaya_odezhda-ASgBAgICAUTeAtgL?q=vetements": (
        "OFF",
        "Vetements — муж.",
        "",
        None,
    ),
    "/rossiya/zapchasti_i_aksessuary/instrumenty-ASgBAgICAUQKxk0": ("OFF", "Автоинструменты", "", None),
    "/rossiya/audio_i_video/kabeli_i_adaptery-ASgBAgICAUSIAs5O": ("OFF", "Адаптеры и кабели", "", None),
    "/rossiya/muzykalnye_instrumenty/akkordeony_garmoni_bayany-ASgBAgICAUTEAsQK": (
        "OFF",
        "Аккордеоны, гармони, баяны",
        "",
        None,
    ),
    "/rossiya/audio_i_video/aksessuary-ASgBAgICAUSIArwJ": ("OFF", "Аксессуары для аудио и видеотехники", "", None),
    "/rossiya/telefony/aksessuari-ASgBAgICAUSwwQ2O_Dc": (
        "OFF",
        "Аксессуары для смартфонов и мобильных телефонов",
        "",
        None,
    ),
    "/rossiya/zapchasti_i_aksessuary/ukhod-ASgBAgICAkQKnk2qlRPU5I0D": (
        "OFF",
        "Аксессуары для ухода за автомобилем",
        "",
        None,
    ),
    "/rossiya/audio_i_video/analogovye_kamery-ASgBAgICAkSIAroJ0sYXsLKaAw": ("OFF", "Аналоговые камеры", "", None),
    "/rossiya/chasy_i_ukrasheniya/bizhuteriya-ASgBAgICAUTQAYoG": ("OFF", "Бижутерия", "", None),
    "/rossiya/audio_i_video/video_dvd_i_blu-ray_pleery-ASgBAgICAUSIArAJ": (
        "OFF",
        "Видео, DVD и Blu-ray плееры",
        "",
        None,
    ),
    "/rossiya/kollektsionirovanie/voennye_veschi-ASgBAgICAUQchgE": ("OFF", "Военная форма и снаряжение", "", None),
    "/rossiya/remont_i_stroitelstvo/vorota_zabory_i_ograzhdeniya-ASgBAgICAURYkpmPAw": (
        "OFF",
        "Ворота, заборы и ограждения",
        "",
        None,
    ),
    "/rossiya/remont_i_stroitelstvo/gotovye_stroeniya_i_sruby-ASgBAgICAURYlrI6": (
        "OFF",
        "Готовые строения и срубы",
        "",
        None,
    ),
    "/rossiya/kollektsionirovanie/gramplastinki-ASgBAgICAUQcjkw": ("OFF", "Грампластинки, винил", "", None),
    "/rossiya/remont_i_stroitelstvo/dveri-ASgBAgICAURYnEs": ("OFF", "Двери", "", None),
    "/rossiya/tovary_dlya_detey_i_igrushki/detskaya_mebel-ASgBAgICAUT~AZQJ": ("OFF", "Детская мебель", "", None),
    "/rossiya/velosipedy/detskie-ASgBAgICAUS4AqoK": ("OFF", "Детские велосипеды", "", None),
    "/rossiya/tovary_dlya_detey_i_igrushki/igrushki-ASgBAgICAUT~AZYJ": ("OFF", "Детские игрушки", "", None),
    "/rossiya/tovary_dlya_detey_i_igrushki/postelnye_prinadlezhnosti-ASgBAgICAUT~AcRP": (
        "OFF",
        "Детские постельные принадлежности",
        "",
        None,
    ),
    "/rossiya/kollektsionirovanie/pepelnicy_zazhigalki-ASgBAgICAUQcoAE": ("OFF", "Зажигалки и пепельницы", "", None),
    "/rossiya/tovary_dlya_zhivotnyh/gryzuny-ASgBAgICAUS8nxfekZkD": ("OFF", "Зоотовары для грызунов", "", None),
    "/rossiya/tovary_dlya_zhivotnyh/pticy-ASgBAgICAUS8nxfgkZkD": ("OFF", "Зоотовары для птиц", "", None),
    "/rossiya/tovary_dlya_zhivotnyh/ryby_i_reptilii-ASgBAgICAUS8nxfikZkD": (
        "OFF",
        "Зоотовары для рыб и рептилий",
        "",
        None,
    ),
    "/rossiya/tovary_dlya_zhivotnyh/sobaki_i_koshki-ASgBAgICAUS8nxfckZkD": (
        "OFF",
        "Зоотовары для собак и кошек",
        "",
        None,
    ),
    "/rossiya/tovary_dlya_zhivotnyh/fermerskoe_khozyaistvo-ASgBAgICAUS8nxfkkZkD": (
        "OFF",
        "Зоотовары для фермерского хозяйства",
        "",
        None,
    ),
    "/rossiya/igry_pristavki_i_programmy/igrovye_pristavki_i_aksessuary-ASgBAgICAUSSAsoJ": (
        "OFF",
        "Игровые приставки и аксессуары",
        "",
        "/rossiya/igry_pristavki_i_programmy/igrovye_pristavki-ASgBAgICAUSSAsoJ",
    ),
    "/rossiya/kollektsionirovanie/kinder-syurpriz-ASgBAgICAUQckAE": ("OFF", "Игрушки из киндер-сюрприз", "", None),
    "/rossiya/kollektsionirovanie/kalendari-ASgBAgICAUQcjgE": ("OFF", "Календари", "", None),
    "/rossiya/remont_i_stroitelstvo/kaminy_i_obogrevateli-ASgBAgICAURYlgI": ("OFF", "Камины и обогреватели", "", None),
    "/rossiya/kollektsionirovanie/kartiny-ASgBAgICAUQcoBc": ("OFF", "Картины и иконы", "", None),
    "/rossiya/kollektsionirovanie/banknoty-ASgBAgICAUQcgAE": ("OFF", "Коллекционные банкноты", "", None),
    "/rossiya/kollektsionirovanie/bilety-ASgBAgICAUQcggE": ("OFF", "Коллекционные билеты", "", None),
    "/rossiya/orgtehnika_i_rashodniki/kopiry-ASgBAgICAkSoAvpO3sENyrE5": ("OFF", "Копиры", "", None),
    "/rossiya/mebel_i_interer/myagkaya_mebel-ASgBAgICAURaqgI": ("OFF", "Кровати, диваны и кресла", "", None),
    "/rossiya/mebel_i_interer/kuhonnye_garnitury-ASgBAgICAURazk8": ("OFF", "Кухни и кухонные гарнитуры", "", None),
    "/rossiya/orgtehnika_i_rashodniki/mfu-ASgBAgICAkSoAvpO3sENxLE5": ("OFF", "МФУ", "", None),
    "/rossiya/mebel_i_interer/drugoe-ASgBAgICAURatgI": ("OFF", "Мебель", "", None),
    "/rossiya/kollektsionirovanie/zhetony_medali_znachki-ASgBAgICAUQcigE": ("OFF", "Медали, жетоны, значки", "", None),
    "/rossiya/audio_i_video/muzyka_i_filmy-ASgBAgICAUSIArQJ": ("OFF", "Музыка и фильмы", "", None),
    "/rossiya/audio_i_video/muzykalnye_tsentry_magnitoly-ASgBAgICAUSIAtJO": (
        "OFF",
        "Музыкальные центры, магнитолы",
        "",
        None,
    ),
    "/rossiya/zapchasti_i_aksessuary/nabor_avtomobilista-ASgBAgICAkQKnk2qlRPO5I0D": (
        "OFF",
        "Наборы автомобилиста для автомобиля",
        "",
        None,
    ),
    "/rossiya/sport_i_otdyh/nagrady_i_kubki-ASgBAgICAUTKAvi5lwM": ("OFF", "Награды и кубки", "", None),
    "/rossiya/sport_i_otdyh/nastolnye_i_kartochnye_igry-ASgBAgICAUTKAoZP": (
        "OFF",
        "Настольные и карточные игры",
        "",
        None,
    ),
    "/rossiya/detskaya_odezhda_i_obuv/odezhda-dlya_devochek-ASgBAgICAUTkAuwL": ("OFF", "Одежда для девочек", "", None),
    "/rossiya/detskaya_odezhda_i_obuv/odezhda-dlya_malchikov-ASgBAgICAUTkAu4L": (
        "OFF",
        "Одежда для мальчиков",
        "",
        None,
    ),
    "/rossiya/remont_i_stroitelstvo/okna_i_balkony-ASgBAgICAURYoEs": ("OFF", "Окна и балконы", "", None),
    "/rossiya/mebel_i_interer/osveschenie-ASgBAgICAURarAI": ("OFF", "Освещение", "", None),
    "/rossiya/audio_i_video/oxrannye_sistemy_i_videonabliudenie-ASgBAgICAkSIAroJ0sYXurKaAw": (
        "OFF",
        "Охранные системы и видеонаблюдение",
        "",
        None,
    ),
    "/rossiya/kollektsionirovanie/plastikovye_kartochki-ASgBAgICAUQcngE": ("OFF", "Пластиковые карточки", "", None),
    "/rossiya/mebel_i_interer/podstavki_i_tumby-ASgBAgICAURargI": ("OFF", "Подставки и тумбы", "", None),
    "/rossiya/posuda_i_tovary_dlya_kuhni/posuda-ASgBAgICAURmzAI": ("OFF", "Посуда", "", None),
    "/rossiya/remont_i_stroitelstvo/potolki-ASgBAgICAURYnks": ("OFF", "Потолки", "", None),
    "/rossiya/kollektsionirovanie/konverty_i_pochtovye_kartochki-ASgBAgICAUQclAE": (
        "OFF",
        "Почтовые конверты и карточки",
        "",
        None,
    ),
    "/rossiya/kollektsionirovanie/otkrytki-ASgBAgICAUQcnAE": ("OFF", "Почтовые открытки", "", None),
    "/rossiya/mebel_i_interer/predmety_interera_iskusstvo-ASgBAgICAURapAI": (
        "OFF",
        "Предметы интерьера и искусства",
        "",
        None,
    ),
    "/rossiya/zapchasti_i_aksessuary/pritsepy-ASgBAgICAUQKyk0": ("OFF", "Прицепы для авто", "", None),
    "/rossiya/orgtehnika_i_rashodniki/mfu_kopiry_i_skanery-ASgBAgICAUSoAvpO": (
        "OFF",
        "Продажа МФУ, копиров, сканеров",
        "",
        None,
    ),
    "/rossiya/tovary_dlya_kompyutera/tv-tyunery-ASgBAgICAUTGB8RO": ("OFF", "Продажа ТВ-тюнеров для ПК", "", None),
    "/rossiya/planshety_i_elektronnye_knigi/aksessuary-ASgBAgICAUSYAopO": (
        "OFF",
        "Продажа аксессуаров для планшетов",
        "",
        None,
    ),
    "/rossiya/tovary_dlya_kompyutera/veb-kamery-ASgBAgICAUTGB7hO": ("OFF", "Продажа веб-камер", "", None),
    "/rossiya/tovary_dlya_kompyutera/perenosnye_zhestkie_diski-ASgBAgICAUTGB8JO": (
        "OFF",
        "Продажа внешних жестких дисков",
        "",
        None,
    ),
    "/rossiya/igry_pristavki_i_programmy/igry_dlya_pristavok-ASgBAgICAUSSAsYJ": (
        "OFF",
        "Продажа игр для приставок",
        "",
        None,
    ),
    "/rossiya/orgtehnika_i_rashodniki/kantselyariya-ASgBAgICAUSoAogK": ("OFF", "Продажа канцтоваров", "", None),
    "/rossiya/tovary_dlya_kompyutera/fleshki_i_karty_pamyati-ASgBAgICAUTGB8ZO": (
        "OFF",
        "Продажа карт памяти и флэшек",
        "",
        None,
    ),
    "/rossiya/tovary_dlya_kompyutera/akustika-ASgBAgICAUTGB7RO": ("OFF", "Продажа компьютерной акустики", "", None),
    "/rossiya/tovary_dlya_kompyutera/aksessuary-ASgBAgICAUTGB5Ro": (
        "OFF",
        "Продажа компьютерных аксессуаров",
        "",
        None,
    ),
    "/rossiya/igry_pristavki_i_programmy/kompyuternye_igry-ASgBAgICAUSSAsgJ": (
        "OFF",
        "Продажа компьютерных игр",
        "",
        None,
    ),
    "/rossiya/igry_pristavki_i_programmy/programmy-ASgBAgICAUSSAs4J": (
        "OFF",
        "Продажа компьютерных программ",
        "",
        None,
    ),
    "/rossiya/orgtehnika_i_rashodniki/printery-ASgBAgICAUSoAoQK": ("OFF", "Продажа принтеров", "", None),
    "/rossiya/orgtehnika_i_rashodniki/rashodnye_materialy-ASgBAgICAUSoAoYK": (
        "OFF",
        "Продажа расходных материалов для оргтехники",
        "",
        None,
    ),
    "/rossiya/orgtehnika_i_rashodniki/ibp_setevye_filtry-ASgBAgICAUSoAv5O": (
        "OFF",
        "Продажа сетевых фильтров и источников питания",
        "",
        None,
    ),
    "/rossiya/orgtehnika_i_rashodniki/telefoniya-ASgBAgICAUSoAvxO": (
        "OFF",
        "Продажа телефонного оборудования",
        "",
        None,
    ),
    "/rossiya/orgtehnika_i_rashodniki/unichtozhiteli_bumag-ASgBAgICAUSoAoBP": ("OFF", "Продажа шредеров", "", None),
    "/rossiya/planshety_i_elektronnye_knigi/elektronnye_knigi-ASgBAgICAUSYAohO": (
        "OFF",
        "Продажа электронных книг",
        "",
        None,
    ),
    "/rossiya/mebel_i_interer/sadovaya_mebel-ASgBAgICAURa6rCXAw": ("OFF", "Садовая мебель", "", None),
    "/rossiya/tovary_dlya_detey_i_igrushki/samokaty_i_begovely-ASgBAgICAUT~AaCGAQ": (
        "OFF",
        "Самокаты и беговелы для детей",
        "",
        None,
    ),
    "/rossiya/remont_i_stroitelstvo/santehnika_i_sauna-ASgBAgICAURYngI": (
        "OFF",
        "Сантехника и товары для сауны",
        "",
        None,
    ),
    "/rossiya/telefony/sim_karty-ASgBAgICAUSwwQ3kq5oD": ("OFF", "Сим-карты", "", None),
    "/rossiya/orgtehnika_i_rashodniki/skanery-ASgBAgICAkSoAvpO3sENyLE5": ("OFF", "Сканеры", "", None),
    "/rossiya/kollektsionirovanie/sportivnye_kartochki-ASgBAgICAUQcogE": ("OFF", "Спортивные карточки", "", None),
    "/rossiya/telefony/statsionarnye_telefoni-ASgBAgICAUSwwQ2M_Dc": ("OFF", "Стационарные телефоны", "", None),
    "/rossiya/mebel_i_interer/stoly_i_stulya-ASgBAgICAURasAI": ("OFF", "Столы и стулья", "", None),
    "/rossiya/remont_i_stroitelstvo/stroymaterialy-ASgBAgICAURYoAI": ("OFF", "Стройматериалы", "", None),
    "/rossiya/mebel_i_interer/tekstil_i_kovry-ASgBAgICAURasgI": ("OFF", "Текстиль, ткани и ковры", "", None),
    "/rossiya/sport_i_otdyh/beg-ASgBAgICAUTKAva5lwM": ("OFF", "Товары для бега", "", None),
    "/rossiya/sport_i_otdyh/bilyard_i_bouling-ASgBAgICAUTKAoJP": ("OFF", "Товары для бильярда и боулинга", "", None),
    "/rossiya/sport_i_otdyh/gimnastika_i_tancy-ASgBAgICAUTKAvC5lwM": (
        "OFF",
        "Товары для гимнастики и танцев",
        "",
        None,
    ),
    "/rossiya/tovary_dlya_detey_i_igrushki/detskaya_gigiena-ASgBAgICAUT~AcqWmAM": (
        "OFF",
        "Товары для детской гигиены",
        "",
        None,
    ),
    "/rossiya/sport_i_otdyh/edinoborstva-ASgBAgICAUTKAoRP": ("OFF", "Товары для единоборств", "", None),
    "/rossiya/sport_i_otdyh/igry_s_myachom-ASgBAgICAUTKAtwK": ("OFF", "Товары для игр с мячом", "", None),
    "/rossiya/sport_i_otdyh/konnyi_sport-ASgBAgICAUTKAvK5lwM": ("OFF", "Товары для конного спорта", "", None),
    "/rossiya/tovary_dlya_detey_i_igrushki/tovary_dlya_kormleniya-ASgBAgICAUT~AZJM": (
        "OFF",
        "Товары для кормления",
        "",
        None,
    ),
    "/rossiya/tovary_dlya_detey_i_igrushki/tovary_dlya_kupaniya-ASgBAgICAUT~AcZP": (
        "OFF",
        "Товары для купания",
        "",
        None,
    ),
    "/rossiya/posuda_i_tovary_dlya_kuhni/tovary_dlya_kuhni-ASgBAgICAURmzgI": ("OFF", "Товары для кухни", "", None),
    "/rossiya/remont_i_stroitelstvo/dlya_sada_i_dachi-ASgBAgICAURYnAI": ("OFF", "Товары для сада и дачи", "", None),
    "/rossiya/sport_i_otdyh/tovary_dlya_otdykha-ASgBAgICAUTKAuIK": ("OFF", "Товары для спорта и отдыха", "", None),
    "/rossiya/sport_i_otdyh/tennis_i_badminton-ASgBAgICAUTKAoxP": ("OFF", "Товары для тенниса и бадминтона", "", None),
    "/rossiya/tovary_dlya_detey_i_igrushki/tovary_dlya_shkoly-ASgBAgICAUT~AchP": ("OFF", "Товары для школы", "", None),
    "/rossiya/mebel_i_interer/shkafy_komodyi_stellazhi-ASgBAgICAURaqAI": ("OFF", "Шкафы и комоды", "", None),
    "/rossiya/audio_i_video/endoskopy-ASgBAgICAkSIAroJ0sYXuLKaAw": ("OFF", "Эндоскопы", "", None),
    "/rossiya/krasota_i_zdorove/bady-ASgBAgICAUSEArSzlwM": (
        "HARD_EXCLUDE",
        "БАДы, пищевые добавки, витаминно-минеральные комплексы",
        "",
        None,
    ),
    "/rossiya/kollektsionirovanie/dokumenty-ASgBAgICAUQciAE": ("HARD_EXCLUDE", "Коллекционные документы", "", None),
    "/rossiya/krasota_i_zdorove/makiyazh_i_manikyur-ASgBAgICAUSEAqIJ": ("HARD_EXCLUDE", "Макияж и маникюр", "", None),
    "/rossiya/krasota_i_zdorove/meditsinskie_izdeliya-ASgBAgICAUSEAqgJ": (
        "HARD_EXCLUDE",
        "Медицинские изделия",
        "",
        None,
    ),
    "/rossiya/kollektsionirovanie/monety-ASgBAgICAUQcmgE": ("HARD_EXCLUDE", "Монеты", "", None),
    "/rossiya/krasota_i_zdorove/parfyumeriya-ASgBAgICAUSEAqYJ": ("HARD_EXCLUDE", "Парфюмерия", "", None),
    "/rossiya/kollektsionirovanie/marki-ASgBAgICAUQclgE": ("HARD_EXCLUDE", "Почтовые марки", "", None),
    "/rossiya/sport_i_otdyh/sportivnoe_pitanie-ASgBAgICAUTKAvK9Ag": ("HARD_EXCLUDE", "Спортивное питание", "", None),
    "/rossiya/krasota_i_zdorove/sredstva_dlya_volos-ASgBAgICAUSEAspP": ("HARD_EXCLUDE", "Средства для волос", "", None),
    "/rossiya/krasota_i_zdorove/ukhod_i_gigiena-ASgBAgICAUSEAqoJ": ("HARD_EXCLUDE", "Уход и гигиена", "", None),
    "/rossiya/chasy_i_ukrasheniya/yuvelirnye_izdeliya-ASgBAgICAUTQAYgG": (
        "HARD_EXCLUDE",
        "Ювелирные украшения",
        "",
        None,
    ),
}

# новые запросы, которых нет в карте (создаются при старте): key -> (scope, name, section, flags)
EXTRA_QUERIES: dict[str, tuple[str, str, str, str]] = {
    "/rossiya?q=dji+mini": ("QUERY", "DJI Mini", "audio_i_video", ""),
    "/rossiya?q=dji+avata": ("QUERY", "DJI Avata", "audio_i_video", ""),
}

# Проверка совпадения для QUERY (ADR-021): поиск Avito «протекает» (Supreme в выдаче Prada). Объявление засчитывается
# запросу, только если в заголовке есть все токены хотя бы одной альтернативы (после нормализации: регистр, ё,
# апострофы и точки убираются — Arc'teryx = arcteryx, C.P. Company = cp company). Ключ — имя запроса до « — ».
QUERY_TERMS: dict[str, tuple[str, ...]] = {
    "Stone Island": ("stone island", "stoneisland", "стон айленд", "стоник"),
    "Rick Owens": ("rick owens", "рик оуэнс", "рик овенс", "drkshdw"),
    "Chrome Hearts": ("chrome hearts", "хром хартс"),
    "Prada": ("prada", "прада"),
    "Miu Miu": ("miu miu", "miumiu", "миу миу"),
    "Maison Margiela": ("margiela", "маржела", "марджела", "mm6"),
    "Arcteryx": ("arcteryx", "arc teryx", "артерикс", "арктерикс"),
    "Moncler": ("moncler", "монклер"),
    "CP Company": ("cp company", "cpcompany", "си пи компани"),
    "Acne Studios": ("acne studios", "acne", "акне"),
    "Fear of God Essentials": ("essentials", "fear of god", "fog"),
    "Represent": ("represent",),
    "Balenciaga": ("balenciaga", "баленсиага"),
    "Gucci": ("gucci", "гуччи"),
    "Louis Vuitton": ("louis vuitton", "lv", "луи виттон"),
    "DJI Mini": ("dji mini",),
    "DJI Avata": ("dji avata",),
}
